set(OSAL_CONFIG_linux_imx6_endpoint_avb         net_avb_endpoint)
set(OSAL_CONFIG_linux_imx6_bridge               net_avb_bridge)
set(OSAL_CONFIG_linux_imx6_hybrid               net_avb_bridge)
set(OSAL_CONFIG_linux_imx6_endpoint_1733        net_avb_endpoint)
set(OSAL_CONFIG_linux_imx6_endpoint_gptp_only   net_avb_endpoint)
set(OSAL_CONFIG_linux_imx8_endpoint_avb         net_avb_endpoint)
set(OSAL_CONFIG_linux_imx8_bridge               net_avb_bridge)
set(OSAL_CONFIG_linux_imx8_hybrid               net_avb_bridge)
set(OSAL_CONFIG_linux_imx8_endpoint_gptp_only   net_avb_endpoint)
set(OSAL_CONFIG_linux_ls1028_bridge             net_std)
set(OSAL_CONFIG_linux_imx6_endpoint_tsn         net_std)
set(OSAL_CONFIG_linux_imx8_endpoint_tsn         net_xdp)
set(OSAL_CONFIG_linux_imx6ull_endpoint_avb      net_avb_endpoint)

if(NOT DEFINED OSAL_CONFIG_${TARGET}_${CONFIG})
  message(FATAL_ERROR "OSAL_CONFIG_${TARGET}_${CONFIG} not defined")
endif()

set(config_file ${CMAKE_CURRENT_LIST_DIR}/config_${OSAL_CONFIG_${TARGET}_${CONFIG}}.cmake)
if(EXISTS ${config_file})
  include(${config_file})
else()
  message(FATAL_ERROR "${config_file} don't exists")
endif()

