mcux_add_source(
    SOURCES
    assert.c
    avb_queue.c
    avb_queue.h
    avtp.c
    avtp.h
    clock.c
    clock.h
    config.h
    debug_print.c
    debug_print.h
    fdb.c
    fqtss.c
    fqtss.h
    frame_preemption.c
    frame_preemption.h
    frer.c
    ftm.c
    ftm.h
    gpt.c
    gpt.h
    gpt_rec.c
    gpt_rec.h
    gptp_dev.c
    gptp_dev.h
    hr_timer.c
    hr_timer.h
    hsr.c
    hsr.h
    hw_clock.c
    hw_clock.h
    hw_timer.c
    hw_timer.h
    imx-pll.h
    ipc.c
    ipc.h
    l2.c
    l2.h
    log.c
    media_clock.h
    media_clock_drv.h
    media_clock_gen_ptp.h
    media_clock_rec_pll.h
    media_queue.h
    mtimer.h
    mrp.c
    mrp.h
    msgintr.c
    msgintr.h
    net.c
    net.h
    net_allocator.c
    net_allocator.h
    net_bridge.c
    net_bridge.h
    net_mdio.c
    net_mdio.h
    net_logical_port.c
    net_logical_port.h
    net_phy.c
    net_phy.h
    net_port.c
    net_port.h
    net_port_dsa.c
    net_port_dsa.h
    net_port_enet.c
    net_port_enet.h
    net_port_enet_mdio.c
    net_port_enet_mdio.h
    net_port_enet_qos.c
    net_port_enet_qos.h
    net_port_enet_qos_mdio.c
    net_port_enet_qos_mdio.h
    net_port_enet_qos_stats.c
    net_port_enet_stats.c
    net_port_enetc_ep.c
    net_port_enetc_ep.h
    net_port_netc_1588.c
    net_port_netc_1588.h
    net_port_netc_mdio.c
    net_port_netc_mdio.h
    net_port_netc_psfp.c
    net_port_netc_psfp.h
    net_port_netc_stats.c
    net_port_netc_stream_identification.c
    net_port_netc_stream_identification.h
    net_port_netc_sw.c
    net_port_netc_sw.h
    net_port_netc_sw_drv.h
    net_port_netc_sw_dsa.c
    net_port_netc_sw_dsa.h
    net_port_netc_sw_frer.c
    net_port_netc_sw_frer.h
    net_port_stats.c
    net_port_stats.h
    net_rx.c
    net_rx.h
    net_socket.c
    net_socket.h
    net_task.c
    net_task.h
    net_tx.c
    net_tx.h
    pi.c
    pi.h
    prng_32.c
    prng_32.h
    psfp.c
    psfp.h
    ptp.c
    ptp.h
    rational.c
    rational.h
    scheduled_traffic.c
    scheduled_traffic.h
    slist.h
    stats_task.c
    stats_task.h
    stdlib.c
    stm.c
    stm.h
    stream_identification.c
    string.c
    timer.c
    tpm.c
    tpm.h
    tpm_rec.c
    tpm_rec.h
    vlan.c
    TOOLCHAINS armgcc mcux
)

if(CONFIG_MCUX_COMPONENT_middleware.genavb.avtp)
    mcux_add_source(
        SOURCES
        imx-pll.c
        media.c
        media_clock.c
        media_clock_gen_ptp.c
        media_clock_rec_pll.c
        media_queue.c
        mtimer.c
        TOOLCHAINS armgcc mcux
    )
endif()
