$(avb-execs)-obj:= aem_helpers.o sr_class.o qos.o helpers.o
$(fslptp-execs)-obj:= qos.o helpers.o
genavb-obj:= sr_class.o qos.o helpers.o
genavb1733-obj:= sr_class.o qos.o helpers.o
api-obj:= sr_class.o
os_subdirs:= linux
