if(NOT DEFINED BIN_DIR)
  message(FATAL_ERROR "BIN_DIR not defined")
endif()

if(NOT DEFINED INITSCRIPT_DIR)
  message(FATAL_ERROR "INITSCRIPT_DIR not defined")
endif()

function(common_scripts_install)
  install(PROGRAMS ${CMAKE_CURRENT_LIST_DIR}/avb.sh DESTINATION ${BIN_DIR})
  install(PROGRAMS ${CMAKE_CURRENT_LIST_DIR}/tsn.sh DESTINATION ${BIN_DIR})
  install(PROGRAMS ${CMAKE_CURRENT_LIST_DIR}/common_func.sh DESTINATION ${CONFIG_DIR})
  # Backward compatibility
  install(CODE "execute_process(COMMAND ln -rsf \$ENV{DESTDIR}/${CMAKE_INSTALL_PREFIX}/${BIN_DIR}/tsn.sh \$ENV{DESTDIR}/${CMAKE_INSTALL_PREFIX}/${BIN_DIR}/fgptp.sh)")
endfunction()

if(${CONFIG} STREQUAL "endpoint_avb")
  common_scripts_install()
  install(PROGRAMS ${CMAKE_CURRENT_LIST_DIR}/init.sh DESTINATION ${INITSCRIPT_DIR} RENAME genavb)
elseif(${CONFIG} STREQUAL "endpoint_tsn" OR ${CONFIG} STREQUAL "endpoint_avb_tsn")
  common_scripts_install()
  install(PROGRAMS ${CMAKE_CURRENT_LIST_DIR}/init.sh DESTINATION ${INITSCRIPT_DIR} RENAME genavb)
  install(PROGRAMS ${CMAKE_CURRENT_LIST_DIR}/tsn-app-setup.sh DESTINATION ${BIN_DIR})
elseif(${CONFIG} STREQUAL "bridge")
  common_scripts_install()
  install(PROGRAMS ${CMAKE_CURRENT_LIST_DIR}/init.sh DESTINATION ${INITSCRIPT_DIR} RENAME genavb)
  install(PROGRAMS ${CMAKE_CURRENT_LIST_DIR}/avb-bridge.sh DESTINATION ${BIN_DIR})
elseif(${CONFIG} STREQUAL "endpoint_avb_tsn_bridge" OR ${CONFIG} STREQUAL "endpoint_avb_tsn_hybrid")
  common_scripts_install()
  install(PROGRAMS ${CMAKE_CURRENT_LIST_DIR}/init.sh DESTINATION ${INITSCRIPT_DIR} RENAME genavb)
  install(PROGRAMS ${CMAKE_CURRENT_LIST_DIR}/tsn-app-setup.sh DESTINATION ${BIN_DIR})
  install(PROGRAMS ${CMAKE_CURRENT_LIST_DIR}/avb-bridge.sh DESTINATION ${BIN_DIR})
elseif(${CONFIG} STREQUAL "hybrid_avb")
  common_scripts_install()
  install(PROGRAMS ${CMAKE_CURRENT_LIST_DIR}/init.sh DESTINATION ${INITSCRIPT_DIR} RENAME genavb)
  install(PROGRAMS ${CMAKE_CURRENT_LIST_DIR}/avb-bridge.sh DESTINATION ${BIN_DIR})
endif()
