archives:= common

common-obj:= timer.o stats.o log.o filter.o managed_objects.o

gptp-obj:= clock.o

avtp-obj:= 61883_iidc.o aaf.o

avdecc-obj:= avdecc.o hash.o

srp-obj:= srp.o

genavb-obj:= 61883_iidc.o log.o avdecc.o aaf.o srp.o


$(avb-execs)-ar:= common.a
$(fgptp-execs)-ar:= common.a
