/*
 * Copyright 2025-2026 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/**
 * @file managed_objects_gptp_lib.c
 * @brief gPTP Managed Objects Decoding Library
 * @details This library provides functions to decode gPTP (Generalized Precision Time Protocol)
 *          managed object names into their corresponding enumeration values. It supports
 *          decoding of nodes names, container names and leaf names, according to
 *          IEEE 802.1AS-2020 standard.
 *
 * The library uses macro-based string comparison for efficient name-to-ID mapping across
 * different gPTP managed object categories.
 */

#include "config.h"

#include <stdlib.h>

#include <stdio.h>

#include "common/managed_objects_gptp.h"

static const char *gptp_top_node_str[GPTP_NODE_MAX] = {
	[GPTP_NODE_INSTANCE_LIST] = GPTP_INSTANCE_LIST_STR,
	[GPTP_NODE_COMMON_SERVICES] = GPTP_COMMON_SERVICES_STR
};

static const char *gptp_instance_container_str[GPTP_INSTANCE_MAX] = {
	[GPTP_INSTANCE_INSTANCE_INDEX] = GPTP_INSTANCE_INDEX_STR,
	[GPTP_INSTANCE_DEFAULT_DS] = GPTP_DEFAULT_DS_STR,
	[GPTP_INSTANCE_CURRENT_DS] = GPTP_CURRENT_DS_STR,
	[GPTP_INSTANCE_PARENT_DS] = GPTP_PARENT_DS_STR,
	[GPTP_INSTANCE_TIME_PROPERTIES_DS] = GPTP_TIME_PROPERTIES_DS_STR,
	[GPTP_INSTANCE_PORTS] = GPTP_PORTS_STR,
};

static const char *gptp_default_ds_str[GPTP_DEFAULT_DS_MAX] = {
	[GPTP_DEFAULT_DS_CLOCK_IDENTITY] = GPTP_DEFAULT_DS_CLOCK_IDENTITY_STR,
	[GPTP_DEFAULT_DS_NUMBER_PORTS] = GPTP_DEFAULT_DS_NUMBER_PORTS_STR,
	[GPTP_DEFAULT_DS_CLOCK_QUALITY] = GPTP_DEFAULT_DS_CLOCK_QUALITY_STR,
	[GPTP_DEFAULT_DS_PRIORITY1] = GPTP_DEFAULT_DS_PRIORITY1_STR,
	[GPTP_DEFAULT_DS_PRIORITY2] = GPTP_DEFAULT_DS_PRIORITY2_STR,
	[GPTP_DEFAULT_DS_DOMAIN_NUMBER] = GPTP_DEFAULT_DS_DOMAIN_NUMBER_STR,
	[GPTP_DEFAULT_DS_CURRENT_TIME] = GPTP_DEFAULT_DS_CURRENT_TIME_STR,
	[GPTP_DEFAULT_DS_GM_CAPABLE] = GPTP_DEFAULT_DS_GM_CAPABLE_STR,
	[GPTP_DEFAULT_DS_CURRENT_UTC_OFFSET] = GPTP_DEFAULT_DS_CURRENT_UTC_OFFSET_STR,
	[GPTP_DEFAULT_DS_CURRENT_UTC_OFFSET_VALID] = GPTP_DEFAULT_DS_CURRENT_UTC_OFFSET_VALID_STR,
	[GPTP_DEFAULT_DS_LEAP59] = GPTP_DEFAULT_DS_LEAP59_STR,
	[GPTP_DEFAULT_DS_LEAP61] = GPTP_DEFAULT_DS_LEAP61_STR,
	[GPTP_DEFAULT_DS_TIME_TRACEABLE] = GPTP_DEFAULT_DS_TIME_TRACEABLE_STR,
	[GPTP_DEFAULT_DS_FREQUENCY_TRACEABLE] = GPTP_DEFAULT_DS_FREQUENCY_TRACEABLE_STR,
	[GPTP_DEFAULT_DS_PTP_TIMESCALE] = GPTP_DEFAULT_DS_PTP_TIMESCALE_STR,
	[GPTP_DEFAULT_DS_TIME_SOURCE] = GPTP_DEFAULT_DS_TIME_SOURCE_STR
};

static const char *gptp_clock_quality_str[GPTP_CLOCK_QUALITY_MAX] = {
	[GPTP_CLOCK_QUALITY_CLOCK_CLASS] = GPTP_CLOCK_QUALITY_CLOCK_CLASS_STR,
	[GPTP_CLOCK_QUALITY_CLOCK_ACCURACY] = GPTP_CLOCK_QUALITY_CLOCK_ACCURACY_STR,
	[GPTP_CLOCK_QUALITY_OFFSET_SCALED_LOG_VARIANCE] = GPTP_CLOCK_QUALITY_OFFSET_SCALED_LOG_VARIANCE_STR,
};

static const char *gptp_current_time_str[GPTP_CURRENT_TIME_MAX] = {
	[GPTP_CURRENT_TIME_SECONDS_FIELD] = GPTP_CURRENT_TIME_SECONDS_FIELD_STR,
	[GPTP_CURRENT_TIME_NANOSECONDS_FIELD] = GPTP_CURRENT_TIME_NANOSECONDS_FIELD_STR,
};

static const char *gptp_current_ds_str[GPTP_CURRENT_DS_MAX] = {
	[GPTP_CURRENT_DS_STEPS_REMOVED] = GPTP_CURRENT_DS_STEPS_REMOVED_STR,
	[GPTP_CURRENT_DS_OFFSET_FROM_TIME_TRANSMITTER] = GPTP_CURRENT_DS_OFFSET_FROM_TIME_TRANSMITTER_STR,
	[GPTP_CURRENT_DS_MEAN_DELAY] = GPTP_CURRENT_DS_MEAN_DELAY_STR,
	[GPTP_CURRENT_DS_LAST_GM_PHASE_CHANGE] = GPTP_CURRENT_DS_LAST_GM_PHASE_CHANGE_STR,
	[GPTP_CURRENT_DS_LAST_GM_FREQ_CHANGE] = GPTP_CURRENT_DS_LAST_GM_FREQ_CHANGE_STR,
	[GPTP_CURRENT_DS_GM_TIMEBASE_INDICATOR] = GPTP_CURRENT_DS_GM_TIMEBASE_INDICATOR_STR,
	[GPTP_CURRENT_DS_GM_CHANGE_COUNT] = GPTP_CURRENT_DS_GM_CHANGE_COUNT_STR,
	[GPTP_CURRENT_DS_TIME_OF_LAST_GM_CHANGE] = GPTP_CURRENT_DS_TIME_OF_LAST_GM_CHANGE_STR,
	[GPTP_CURRENT_DS_TIME_OF_LAST_PHASE_CHANGE] = GPTP_CURRENT_DS_TIME_OF_LAST_PHASE_CHANGE_STR,
	[GPTP_CURRENT_DS_TIME_OF_LAST_FREQ_CHANGE] = GPTP_CURRENT_DS_TIME_OF_LAST_FREQ_CHANGE_STR
};

static const char *gptp_parent_ds_str[GPTP_PARENT_DS_MAX] = {
	[GPTP_PARENT_DS_PARENT_PORT_IDENTITY] = GPTP_PARENT_DS_PARENT_PORT_IDENTITY_STR,
	[GPTP_PARENT_DS_PARENT_STATS] = GPTP_PARENT_DS_PARENT_STATS_STR,
	[GPTP_PARENT_DS_GRANDMASTER_IDENTITY] = GPTP_PARENT_DS_GRANDMASTER_IDENTITY_STR,
	[GPTP_PARENT_DS_GRANDMASTER_CLOCK_QUALITY] = GPTP_PARENT_DS_GRANDMASTER_CLOCK_QUALITY_STR,
	[GPTP_PARENT_DS_GRANDMASTER_PRIORITY1] = GPTP_PARENT_DS_GRANDMASTER_PRIORITY1_STR,
	[GPTP_PARENT_DS_GRANDMASTER_PRIORITY2] = GPTP_PARENT_DS_GRANDMASTER_PRIORITY2_STR,
	[GPTP_PARENT_DS_CUMULATIVE_RATE_RATIO] = GPTP_PARENT_DS_CUMULATIVE_RATE_RATIO_STR
};

static const char *gptp_port_identity_str[GPTP_PORT_IDENTITY_MAX] = {
	[GPTP_PORT_IDENTITY_CLOCK_IDENTITY] = GPTP_PORT_IDENTITY_CLOCK_IDENTITY_STR,
	[GPTP_PORT_IDENTITY_PORT_NUMBER] = GPTP_PORT_IDENTITY_PORT_NUMBER_STR,
};

static const char *gptp_time_properties_ds_str[GPTP_TIME_PROPERTIES_DS_MAX] = {
	[GPTP_TIME_PROPERTIES_DS_CURRENT_UTC_OFFSET] = GPTP_TIME_PROPERTIES_DS_CURRENT_UTC_OFFSET_STR,
	[GPTP_TIME_PROPERTIES_DS_CURRENT_UTC_OFFSET_VALID] = GPTP_TIME_PROPERTIES_DS_CURRENT_UTC_OFFSET_VALID_STR,
	[GPTP_TIME_PROPERTIES_DS_LEAP59] = GPTP_TIME_PROPERTIES_DS_LEAP59_STR,
	[GPTP_TIME_PROPERTIES_DS_LEAP61] = GPTP_TIME_PROPERTIES_DS_LEAP61_STR,
	[GPTP_TIME_PROPERTIES_DS_TIME_TRACEABLE] = GPTP_TIME_PROPERTIES_DS_TIME_TRACEABLE_STR,
	[GPTP_TIME_PROPERTIES_DS_FREQUENCY_TRACEABLE] = GPTP_TIME_PROPERTIES_DS_FREQUENCY_TRACEABLE_STR,
	[GPTP_TIME_PROPERTIES_DS_TIME_SOURCE] = GPTP_TIME_PROPERTIES_DS_TIME_SOURCE_STR
};

static const char *gptp_ports_str[GPTP_PORTS_MAX] = {
	[GPTP_PORTS_PORT] = GPTP_PORTS_PORT_STR
};

static const char *gptp_port_str[GPTP_PORT_MAX] = {
	[GPTP_PORT_PORT_INDEX] = GPTP_PORT_PORT_INDEX_STR,
	[GPTP_PORT_PORT_DS] = GPTP_PORT_PORT_DS_STR,
	[GPTP_PORT_PORT_STATS_DS] = GPTP_PORT_PORT_STATS_DS_STR
};

static const char *gptp_port_ds_str[GPTP_PORT_DS_MAX] = {
	[GPTP_PORT_DS_PORT_IDENTITY] = GPTP_PORT_DS_PORT_IDENTITY_STR,
	[GPTP_PORT_DS_PORT_STATE] = GPTP_PORT_DS_PORT_STATE_STR,
	[GPTP_PORT_DS_MEAN_LINK_DELAY] = GPTP_PORT_DS_MEAN_LINK_DELAY_STR,
	[GPTP_PORT_DS_LOG_ANNOUNCE_INTERVAL] = GPTP_PORT_DS_LOG_ANNOUNCE_INTERVAL_STR,
	[GPTP_PORT_DS_ANNOUNCE_RECEIPT_TIMEOUT] = GPTP_PORT_DS_ANNOUNCE_RECEIPT_TIMEOUT_STR,
	[GPTP_PORT_DS_LOG_SYNC_INTERVAL] = GPTP_PORT_DS_LOG_SYNC_INTERVAL_STR,
	[GPTP_PORT_DS_VERSION_NUMBER] = GPTP_PORT_DS_VERSION_NUMBER_STR,
	[GPTP_PORT_DS_DELAY_ASYMMETRY] = GPTP_PORT_DS_DELAY_ASYMMETRY_STR,
	[GPTP_PORT_DS_PORT_ENABLED] = GPTP_PORT_DS_PORT_ENABLED_STR,
	[GPTP_PORT_DS_IS_MEASURING_DELAY] = GPTP_PORT_DS_IS_MEASURING_DELAY_STR,
	[GPTP_PORT_DS_AS_CAPABLE] = GPTP_PORT_DS_AS_CAPABLE_STR,
	[GPTP_PORT_DS_MEAN_LINK_DELAY_THRESH] = GPTP_PORT_DS_MEAN_LINK_DELAY_THRESH_STR,
	[GPTP_PORT_DS_NEIGHBOR_RATE_RATIO] = GPTP_PORT_DS_NEIGHBOR_RATE_RATIO_STR,
	[GPTP_PORT_DS_INITIAL_LOG_ANNOUNCE_INTERVAL] = GPTP_PORT_DS_INITIAL_LOG_ANNOUNCE_INTERVAL_STR,
	[GPTP_PORT_DS_CURRENT_LOG_ANNOUNCE_INTERVAL] = GPTP_PORT_DS_CURRENT_LOG_ANNOUNCE_INTERVAL_STR,
	[GPTP_PORT_DS_INITIAL_LOG_SYNC_INTERVAL] = GPTP_PORT_DS_INITIAL_LOG_SYNC_INTERVAL_STR,
	[GPTP_PORT_DS_CURRENT_LOG_SYNC_INTERVAL] = GPTP_PORT_DS_CURRENT_LOG_SYNC_INTERVAL_STR,
	[GPTP_PORT_DS_SYNC_RECEIPT_TIMEOUT] = GPTP_PORT_DS_SYNC_RECEIPT_TIMEOUT_STR,
	[GPTP_PORT_DS_SYNC_RECEIPT_TIMEOUT_TIME_INTERVAL] = GPTP_PORT_DS_SYNC_RECEIPT_TIMEOUT_TIME_INTERVAL_STR,
	[GPTP_PORT_DS_INITIAL_LOG_PDELAY_REQ_INTERVAL] = GPTP_PORT_DS_INITIAL_LOG_PDELAY_REQ_INTERVAL_STR,
	[GPTP_PORT_DS_CURRENT_LOG_PDELAY_REQ_INTERVAL] = GPTP_PORT_DS_CURRENT_LOG_PDELAY_REQ_INTERVAL_STR,
	[GPTP_PORT_DS_ALLOWED_LOST_RESPONSES] = GPTP_PORT_DS_ALLOWED_LOST_RESPONSES_STR,
	[GPTP_PORT_DS_ALLOWED_FAULTS] = GPTP_PORT_DS_ALLOWED_FAULTS_STR
};

static const char *gptp_port_statistics_ds_str[GPTP_PORT_STATS_DS_MAX] = {
    [GPTP_PORT_STATS_DS_RX_SYNC_COUNT] = GPTP_PORT_STATS_DS_RX_SYNC_COUNT_STR,
    [GPTP_PORT_STATS_DS_RX_FOLLOW_UP_COUNT] = GPTP_PORT_STATS_DS_RX_FOLLOW_UP_COUNT_STR,
    [GPTP_PORT_STATS_DS_RX_PDELAY_REQUEST_COUNT] = GPTP_PORT_STATS_DS_RX_PDELAY_REQUEST_COUNT_STR,
    [GPTP_PORT_STATS_DS_RX_PDELAY_RESPONSE_COUNT] = GPTP_PORT_STATS_DS_RX_PDELAY_RESPONSE_COUNT_STR,
    [GPTP_PORT_STATS_DS_RX_PDELAY_RESPONSE_FOLLOW_UP_COUNT] = GPTP_PORT_STATS_DS_RX_PDELAY_RESPONSE_FOLLOW_UP_COUNT_STR,
    [GPTP_PORT_STATS_DS_RX_ANNOUNCE_COUNT] = GPTP_PORT_STATS_DS_RX_ANNOUNCE_COUNT_STR,
    [GPTP_PORT_STATS_DS_RX_PACKET_DISCARD_COUNT] = GPTP_PORT_STATS_DS_RX_PACKET_DISCARD_COUNT_STR,
    [GPTP_PORT_STATS_DS_SYNC_RECEIPT_TIMEOUT_COUNT] = GPTP_PORT_STATS_DS_SYNC_RECEIPT_TIMEOUT_COUNT_STR,
    [GPTP_PORT_STATS_DS_ANNOUNCE_RECEIPT_TIMEOUT_COUNT] = GPTP_PORT_STATS_DS_ANNOUNCE_RECEIPT_TIMEOUT_COUNT_STR,
    [GPTP_PORT_STATS_DS_PDELAY_ALLOWED_LOST_RESPONSES_EXCEEDED_COUNT] = GPTP_PORT_STATS_DS_PDELAY_ALLOWED_LOST_RESPONSES_EXCEEDED_COUNT_STR,
    [GPTP_PORT_STATS_DS_TX_SYNC_COUNT] = GPTP_PORT_STATS_DS_TX_SYNC_COUNT_STR,
    [GPTP_PORT_STATS_DS_TX_FOLLOW_UP_COUNT] = GPTP_PORT_STATS_DS_TX_FOLLOW_UP_COUNT_STR,
    [GPTP_PORT_STATS_DS_TX_PDELAY_REQUEST_COUNT] = GPTP_PORT_STATS_DS_TX_PDELAY_REQUEST_COUNT_STR,
    [GPTP_PORT_STATS_DS_TX_PDELAY_RESPONSE_COUNT] = GPTP_PORT_STATS_DS_TX_PDELAY_RESPONSE_COUNT_STR,
    [GPTP_PORT_STATS_DS_TX_PDELAY_RESPONSE_FOLLOW_UP_COUNT] = GPTP_PORT_STATS_DS_TX_PDELAY_RESPONSE_FOLLOW_UP_COUNT_STR,
    [GPTP_PORT_STATS_DS_TX_ANNOUNCE_COUNT] = GPTP_PORT_STATS_DS_TX_ANNOUNCE_COUNT_STR
};

/* Sub-container descriptors for default-ds */
static const struct genavb_mobj_node_descriptor gptp_default_ds_children[] = {
	[GPTP_DEFAULT_DS_CLOCK_QUALITY] = {
		.self = GPTP_DEFAULT_DS_CLOCK_IDENTITY_STR,
		.names = gptp_clock_quality_str,
		.max_id = GPTP_CLOCK_QUALITY_MAX,
		.children = NULL,
		.num_children = 0
	},
	[GPTP_DEFAULT_DS_CURRENT_TIME] = {
		.self = GPTP_DEFAULT_DS_CURRENT_TIME_STR,
		.names = gptp_current_time_str,
		.max_id = GPTP_CURRENT_TIME_MAX,
		.children = NULL,
		.num_children = 0
	}
};

/* Sub-container descriptors for parent-ds */
static const struct genavb_mobj_node_descriptor gptp_parent_ds_children[] = {
	[GPTP_PARENT_DS_PARENT_PORT_IDENTITY] = {
		.self = GPTP_PARENT_DS_PARENT_PORT_IDENTITY_STR,
		.names = gptp_port_identity_str,
		.max_id = GPTP_PORT_IDENTITY_MAX,
		.children = NULL,
		.num_children = 0
	},
	[GPTP_PARENT_DS_GRANDMASTER_CLOCK_QUALITY] = {
		.self = GPTP_PARENT_DS_GRANDMASTER_IDENTITY_STR,
		.names = gptp_clock_quality_str,
		.max_id = GPTP_CLOCK_QUALITY_MAX,
		.children = NULL,
		.num_children = 0
	}
};

/* Sub-container descriptors for port-ds */
static const struct genavb_mobj_node_descriptor gptp_port_ds_children[] = {
	[GPTP_PORT_DS_PORT_IDENTITY] = {
		.self = GPTP_PORT_DS_PORT_IDENTITY_STR,
		.names = gptp_port_identity_str,
		.max_id = GPTP_PORT_IDENTITY_MAX,
		.children = NULL,
		.num_children = 0
	},
};

static const struct genavb_mobj_node_descriptor gptp_port_children[] = {
	[GPTP_PORT_PORT_DS] = {
		.self = GPTP_PORT_PORT_DS_STR,
		.names = gptp_port_ds_str,
		.max_id = GPTP_PORT_DS_MAX,
		.children = gptp_port_ds_children,
		.num_children = sizeof(gptp_port_ds_children) / sizeof(gptp_port_ds_children[0])
	},
	[GPTP_PORT_PORT_STATS_DS] = {
		.self = GPTP_PORT_PORT_STATS_DS_STR,
		.names = gptp_port_statistics_ds_str,
		.max_id = GPTP_PORT_STATS_DS_MAX,
		.children = NULL,
		.num_children = 0
	}
};

static const struct genavb_mobj_node_descriptor gptp_ports_children[] = {
	[GPTP_PORTS_PORT] = {
		.self = GPTP_PORTS_PORT_STR,
		.names = gptp_port_str,
		.max_id = GPTP_PORT_MAX,
		.children = gptp_port_children,
		.num_children = sizeof(gptp_port_children) / sizeof(gptp_port_children[0])
	},
};

/* Instance container children */
static const struct genavb_mobj_node_descriptor gptp_instance_children[] = {
	[GPTP_INSTANCE_DEFAULT_DS] = {
		.self = GPTP_DEFAULT_DS_STR,
		.names = gptp_default_ds_str,
		.max_id = GPTP_DEFAULT_DS_MAX,
		.children = gptp_default_ds_children,
		.num_children = sizeof(gptp_default_ds_children) / sizeof(gptp_default_ds_children[0])
	},
	[GPTP_INSTANCE_CURRENT_DS] = {
		.self = GPTP_CURRENT_DS_STR,
		.names = gptp_current_ds_str,
		.max_id = GPTP_CURRENT_DS_MAX,
		.children = NULL,
		.num_children = 0
	},
	[GPTP_INSTANCE_PARENT_DS] = {
		.self = GPTP_PARENT_DS_STR,
		.names = gptp_parent_ds_str,
		.max_id = GPTP_PARENT_DS_MAX,
		.children = gptp_parent_ds_children,
		.num_children = sizeof(gptp_parent_ds_children) / sizeof(gptp_parent_ds_children[0])
	},
	[GPTP_INSTANCE_TIME_PROPERTIES_DS] = {
		.self = GPTP_TIME_PROPERTIES_DS_STR,
		.names = gptp_time_properties_ds_str,
		.max_id = GPTP_TIME_PROPERTIES_DS_MAX,
		.children = NULL,
		.num_children = 0
	},
	[GPTP_INSTANCE_PORTS] = {
		.self = GPTP_PORTS_STR,
		.names = gptp_ports_str,
		.max_id = GPTP_PORTS_MAX,
		.children = gptp_ports_children,
		.num_children = sizeof(gptp_ports_children) / sizeof(gptp_ports_children[0])
	},
};

/* Top level nodes */
static const struct genavb_mobj_node_descriptor gptp_top_children[] = {
	[GPTP_NODE_INSTANCE_LIST] = {
		.self = GPTP_INSTANCE_LIST_STR,
		.names = gptp_instance_container_str,
		.max_id = GPTP_INSTANCE_MAX,
		.children = gptp_instance_children,
		.num_children = sizeof(gptp_instance_children) / sizeof(gptp_instance_children[0])
	},
	[GPTP_NODE_COMMON_SERVICES] = {
		.self = GPTP_COMMON_SERVICES_STR,
		.names = NULL,
		.max_id = 0,
		.children = NULL,
		.num_children = 0
	}
};

const struct genavb_mobj_node_descriptor gptp_top_nodes_descriptor = {
	.self = "top container",
	.names = gptp_top_node_str,
	.max_id = GPTP_NODE_MAX,
	.children = gptp_top_children,
	.num_children = sizeof(gptp_top_children) / sizeof(gptp_top_children[0])
};
